### ISSUE TITLE
concat_native / concat conflict

### ISSUE THREAD

**Issue by j-vizcaino** [theforeman/puppet-concat_native#10]
Hi,

It seems using concat_native and concat (from PuppetLabs) leads to a conflict as they both use the same directory to store fragments and script.

Is there a reason for using `concat_native` instead of the "official" `concat` module in the Foreman puppet modules (apart from historical choice) ?

I see two options:

* move codebase to `concat` (quite easy as the API is almost equivalent)
* patch `concat_native` to avoid the conflict (I have this at work, I can create a PR if needed)

Thanks

Jérôme

**Comment by ekohl** [comment]
I have used both in production for a long time and so far haven't noticed any conflicts. Could you point out where the conflict is?

**Comment by j-vizcaino** [comment]
They use the same work dir, `Puppet[:vardir]/concat`
`concat` purges unknown files located in this folder and, as `concat_native` creates files there without declaring them in Puppet, those files are removed.
As a result, hosts using both modules are always *active* in Foreman.

**Comment by ekohl** [comment]
That might be a new thing, but then I think concat_native should be patched. A PR would be highly appreciated.

**Comment by j-vizcaino** [comment]
The patch I applied simply consisted in renaming the concat dir to `concat_native`.
This way both modules can have their separate runtime dirs and not interfere with each other.
Is that ok with you ?
I'll create the PR during the week.

**Comment by ekohl** [comment]
That sounds like the easiest solution. It may be a leftover from when this module was also (confusingly) called concat. We already renamed the repo and that patch would complete the process.
