### ISSUE TITLE
concat_native / concat conflict (#2)

### ISSUE THREAD

**Issue by Thubo** [theforeman/puppet-concat_native#12]
Hi there,

I tried to use concat and concat_native in parallel.

It works fine with concat 1.2.x the latest concat_native, however if you use the latest concat (master branch), the following files will overwrite each other:

https://github.com/puppetlabs/puppetlabs-concat/tree/master/lib/puppet/type
vs
https://github.com/theforeman/puppet-concat_native/tree/master/lib/puppet/type

The simple solution for now is to use the concat 1.2.x branch, however I guess it would be nice to recreate the compatibility.

Thanks a lot
Cheers

**Comment by domcleal** [comment]
We're unlikely to fix this, as we're beginning to migrate our own modules to use puppetlabs-concat 2.x.

**Comment by ekohl** [comment]
Also note that puppetlabs-concat 2.0 is supposed to be faster as well so it'd be good for to community to converge on one solution.

**Comment by domcleal** [comment]
I filed #13 to officially mark this module as deprecated, and our own modules are now in the process of moving to pl-concat (foreman/puppet both done, dhcp/dns in progress).  I've also opened PRs against our deps to migrate them to pl-concat 2.x.

Thanks for raising this, sorry for the compatibility, but I think we're now on the right track with pl-concat 2.x.
