### ISSUE TITLE
DEPRECATED but still updated

### ISSUE THREAD

**Issue by SydOps** [theforeman/puppet-concat_native#14]
Hi 

One of my project is using this module and I need know if I can continue to use it.

The repository is marked as DEPRECATED, but I can still see the new commits recently.

So related with `puppetlabs-concat`, there are two latest release: 1.2.3 and 2.0.1

Does it mean if I lock on `puppetlabs-concat release 1.2.3`, I should be fine with your latest commits?

**Comment by ekohl** [comment]
That should be no problem. We have no more need for it so that means over time the quality may suffer and support for newer puppet versions could become a problem. I have no problem accepting commits but we will no longer actively develop it.

Does that answer your question?

**Comment by SydOps** [comment]
in fact, I have one more question. 

We plan to upgrade the puppet version to 4.0, and currently reviewing the share modules, I need know if this module will work with puppet 4 or not.

**Comment by ekohl** [comment]
Puppet 4 support is something we need to sort out in most of our modules. It may work, but I'm not aware of anyone who tested it.
